In [54]:
#creating the arena 
import random 
import numpy as np
import math
random.seed(42)
#creates the arena using zeros 
n=int(input('please enter the size of arena '))
def arena(n):
    arena=np.zeros((n,n))
    return arena    
arena=arena(n)
print(arena)

please enter the size of arena 10
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
#moving the players
NumberOfPlayers=int(input("please enter the nuber of players "))
#[(number of the player, dead 1 or alive 0 , players killed , i cordinate , j cordinate)] 
players=[]
for i in range(0,NumberOfPlayers):
    temp=[i+1,0,0,random.randint(0,n),random.randint(0,n)]
    players.append(temp)
def move(player):
    movement=random.randint(1,4)
    if(movement == 1):
        player[3]=player[3]+1#up
    elif(movement == 2):
        player[3]=player[3]-1#down
    elif(movement == 3):
        player[4]=player[4]+1#right
    elif(movement == 4):
        player[4]=player[4]-1#left

please enter the nuber of players 5


In [59]:
players

[[1, 0, 0, 0, 8],
 [2, 0, 0, 3, 10],
 [3, 0, 0, 8, 6],
 [4, 0, 0, 3, 7],
 [5, 0, 0, 9, 4]]

In [60]:
#killig process 
#[(number of the player, dead 1 or alive 0 , players killed , i cordinate , j cordinate)] 

killed_players=0 #the number of killed players in general
#used to keep track of the killed players 
#when it's equal to n-1 (number of players - 1) the game will finish
def kill(player1,player2):
    point1=[]
    point2=[]
    point1.append(player1[2]);point1.append(player1[3])
    point2.append(player2[2]);point2.append(player2[3])

###############################################################
    distance= math.dist(point1,point2)
    if distance<=1:
        kill=random.uniform(0, 1)
        if kill>0.5:
            #player 1 is killed
            killed_players=killed_players+1
            player1[2]=player1[2]+1 #adding one to the number of killed players by player 1
            player2[1]=1#player 2 is dead now 
        else:
            #player 2 is killed
            killed_players=killed_players+1 
            player2[2]=player2[2]+1 #adding one to the number of killed players by player 2
            player1[1]=1 #player 1 is dead 

In [23]:
#simulation phase
game=True
while(game):
    for i in range (0,n):
        player=players[i+1] #players move
        move(player)
    kill(player1,player2)
    if killed_players==NumberOfPlayers-1:
    game=False

TypeError: list indices must be integers or slices, not tuple

In [61]:
#stuff left to deal with:
#how to do the simulation
#how to do the killing process for all of them