In [29]:
#creating the arena 
import random 
import numpy as np
import math
random.seed(42)
#creates the arena using zeros 
n=int(input('please enter the size of arena '))
def arena(n):
    arena=np.zeros((n,n))
    return arena    
arena=arena(n)
print(arena)

please enter the size of arena 10
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
#moving the players
NumberOfPlayers=int(input("please enter the nuber of players"))
#should make a list of tuples 
#[(dead 1 or alive 0 , players killed , i cordinate , j cordinate)] 
#the code is written for only two players but will be completed for more that two 
# players= np.reshape(np.arange(NumberOfPlayers*1*4), (NumberOfPlayers,1,4))
players=[]
for i in range(0,NumberOfPlayers):
    temp=[i+1,0,random.randint(0,n),random.randint(0,n)]
    players.append(temp)
def move(player):
    movement=random.randint(1,4)
    if(movement == 1):
        player[2]=player[2]+1#up
    elif(movement == 2):
        player[2]=player[2]-1#down
    elif(movement == 3):
        player[3]=player[3]+1#right
    elif(movement == 4):
        player[3]=player[3]-1#left

please enter the nuber of players4


In [36]:
players

[[1, 0, 8, 9], [2, 0, 0, 8], [3, 0, 3, 10], [4, 0, 8, 6]]

In [48]:
player=players[0]
player[2]=player[2]+1
player

[1, 0, 9, 9]

In [22]:
#killig process 
killed_players=0
def kill(player1,player2):
    distance= math.dist(player1,player2)
    if distance<=1:
        kill=random.uniform(0, 1)
        if kill>0.5:
            print("player 1 is killed")
            player2_kills=player2_kills+1
            killed_players=killed_players+1
        else:
            print("player 2 is killed")
            player1_kills=player1_kills+1
            killed_players=killed_players+1

In [23]:
#simulation phase
game=True
while(game):
    move(player1)
    move(player2)
    kill(player1,player2)
    if killed_players==NumberOfPlayers-1:
        game=False


TypeError: list indices must be integers or slices, not tuple